apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app-canary
  labels:
    app: inventario-app
    version: canary
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: inventario-app
      version: canary

  template:
    metadata:
      labels:
        app: inventario-app
        version: canary

    spec:
      containers:
        - name: inventario-app
          image: ghcr.io/cabreram14/inventario-app:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: APP_VERSION
              value: "v2-canary"

            - name: APP_COLOR
              value: "green"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"